import { useRouteLoaderData } from '@remix-run/react';
import { SelectPlayer } from '~/.server/db/schema';
import { DeletePlayerForm } from './DeletePlayerForm';
import { loader } from '~/routes/_index';

/**
 * Players component
 *
 * @returns React component
 */
export function Players() {
  // Get the players data from the route loader
  // Route ids are auto generated by remix (e.g. routes/_index)
  const { players } = useRouteLoaderData<typeof loader>('routes/_index') as {
    players: Array<SelectPlayer>;
  };

  if (players.length === 0) {
    return (
      <p className="text-center">
        No players in the database. <br /> Use the form to add some.
      </p>
    );
  }

  return (
    <ul className="flex flex-col gap-2 text-center">
      {players.map((player) => (
        <li
          key={player.id}
          className="border bg-gray-50 p-2 flex justify-between gap-10"
        >
          {player.name}
          <DeletePlayerForm playerId={player.id} />
        </li>
      ))}
    </ul>
  );
}
